name: Deploy Lambda via OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::310318660616:role/GithubActionsDeployRole
          aws-region: eu-central-1

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Compile and Package Go Lambda
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o bootstrap . 

          zip deployment-package.zip bootstrap

      - name: Update Lambda Function Code and Configuration
        run: |
          aws lambda update-function-code \
            --function-name hello-world \
            --zip-file fileb://deployment-package.zip

          aws lambda update-function-configuration \
            --function-name hello-world \
            --runtime go1.x \
            --handler bootstrap
